#!/usr/bin/env bash
# Displays information about subdomains
get_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local result
    result=$(dig "$subdomain.$domain" | awk '/ANSWER SECTION:/{getline; print}')
    local record_type
    record_type=$(echo "$result" | awk '{print $4}')
    local destination
    destination=$(echo "$result" | awk '{print $5}')
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ -z "$2" ]; then
    get_subdomain_info "$1" "www"
    get_subdomain_info "$1" "lb-01"
    get_subdomain_info "$1" "web-01"
    get_subdomain_info "$1" "web-02"
else
    get_subdomain_info "$1" "$2"
fi